version: '3.8'

services:
  enerfris-single-postgresql-db:
    container_name: enerfris-single-postgresql-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - ./enerfris-single-postgresql-db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - enerfris-single-postgresql

  enerfris-single-postgresql-pgadmin:
    container_name: enerfris-single-postgresql-pgadmin
    restart: always
    image: dpage/pgadmin4:8.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - enerfris-single-postgresql-db
    ports:
      - ${PG_ADMIN_PORT}:80
    networks:
      - enerfris-single-postgresql
    volumes:
      -  pgadmin:/var/lib/pgadmin
    user: "root:root"

networks:
  enerfris-single-postgresql:
    name: enerfris-single-postgresql

volumes:
  pgadmin:

